# theme: jekyll-theme-cayman

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Front end Developer Interview Questions
email: marcelo@marcelocarmona.com
description: > # this means to ignore newlines until "baseurl:"
  A list of helpful front-end related questions you can use to interview potential candidates, test yourself or completely ignore.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://marcelocarmona.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
collections:
  questions:
    output: true
    permalink: /:path
